### ISSUE TITLE
v1.14 Auto Scan Bug

### ISSUE THREAD

**Issue by makaristo** [goshante/ats20_ats_ex#1]
First of all, thank you for your work and efforts.  I encountered a bug in v1.14 version.  In this version, the frequency on the screen does not update itself when automatic station scanning is performed.  Scanning of the station can be heard in the background.  It captures the frequency, but the frequency information cannot be seen.  After the version upgrade, I reset the device.  But the situation has not changed. 

Also, if possible, if the SW intermediate band sections are removed, transitions between modes will take less time.  There are currently 1M frequency steps available.  In this way, the desired frequency can be reached.
Sorry for my english.
I wish you success in your work and thank you again. 
Kind regards.

**Comment by goshante** [comment]
Frequency is dynamically updated while scanning, tested on latest version of my firmware. I can see frequency steps while it performs scanning. Sorry, cannot reproduce this bug. Might be a hardware related issue.
Thank you for your problem report.

You can quickly navigate between SW subbands in band adjustment mode (not only 1M steps). Just press BAND+ and rotate encoder.
