### ISSUE TITLE
Firmware for OLED monitors 128x32

### ISSUE THREAD

**Issue by UD3SBV** [goshante/ats20_ats_ex#11]
Hello! Could you modify your firmware for my FOX receiver. I really liked your firmware, I would like it for a 128x32 OLED display and control without buttons, only one encoder. If possible, write to me at ud3svb@gmail.co
![1](https://github.com/goshante/ats20_ats_ex/assets/112188814/2aac54e5-8ce9-452f-86b6-61230d48f521)
![2](https://github.com/goshante/ats20_ats_ex/assets/112188814/ded8cf02-e75a-46c7-8f2b-7c1af894bdf9)
m

**Comment by goshante** [comment]
You can do it yourself, sources are available in repository here.
I don't have this display so I cannot do this properly and test it.
