### ISSUE TITLE
Frequency Shift

### ISSUE THREAD

**Issue by Kris1958** [goshante/ats20_ats_ex#14]
Much appreciation for the work.

I noticed a 1.5 kHz downshift for correctly when listening to a station in SSB.
Can you fix this?
BFO = 0.

Checked with professional shortwave equipment.

Best regards
Kris1958

**Comment by goshante** [comment]
This is a bug of Si4732 chip. To fix this I have to align frequency by correction table. To do that I need more space for storing table and new logic, this is not possible to do that without cutting other features.

**Comment by Kris1958** [comment]
Hello, 

Thank you for the information.

I hope you can do it.

Good luck and thank you for the great work you have already done.

 

Regards

Kris
