### ISSUE TITLE
AIR BAND

### ISSUE THREAD

**Issue by pu3agg** [goshante/ats20_ats_ex#16]
Can do match the ats20+ to sintonize and hear Air band in AM Mode? 

118mhz - up

**Comment by G8PTN** [comment]
Hi,
To receive the air band in AM mode you would need to have a down converter to move the frequency into the HF band, which supports narrow band AM demodulation.

It would be possible to build a mixer circuit with a programmable oscillator, similar to those proposed on the ATS25 receivers. Unfortunately on the ATS20 the additional firmware required to control the oscillator probably would not fit in the code space of the Nano without removing other features.

Relatively low cost down converters are available, see example below. This would not require any firmware or hardware changes. Two versions of the down converter are available, 100MHz and 110MHz.
For example using the 100MHz version, to listen to 120MHz, you would tune to 20MHz on the ATS20.
https://www.youtube.com/watch?v=JILgwTiw1cM

73, Dave
