### ISSUE TITLE
i need 2.4k BW on SSB 

### ISSUE THREAD

**Issue by dickiemickiedami** [goshante/ats20_ats_ex#27]
every ham band user sounds really hight pitched beacause the operate at 2.4khz and the firmware doesnt have 2.4 khz option

**Comment by G8PTN** [comment]
Hi,
My understanding is that the SSB patch used for the SI473x only supports the audio filter options as shown below.
This is the same for all SI473x based solutions.

![image](https://github.com/user-attachments/assets/41269c84-e49c-4909-a48f-5deb9d74b265)

Reference: https://pu2clr.github.io/SI4735/extras/apidoc/html/group__group17.html#ga7554815b6d83128c5b15206e69c51f9f

73, Dave

**Comment by dickiemickiedami** [comment]
thanks didnt know that about the si473x 

73, damian
