### ISSUE TITLE
Arduino Nano replaced Maker Nano RP2040

### ISSUE THREAD

**Issue by dinosauria123** [goshante/ats20_ats_ex#9]
Hi,
Thank you for your good work.

I try to replace ATS-20 Plus microcontroller Arduino Nano to Maker Nano RP2040, it works fine.

I modified your source to fit RP2040 pin out. 

The good is overcome memory size limitation. Your program used only 3-4 % of RP2040 memory.

The bad is Maker Nano RP2040 is slightly longer than Arduino Nano, I could not close rear panel...

We can also use ESP32-Nano, which has WIFI & BT as the same size of Arduino Nano.

I hope you are interested in my (dirty) work.

[ATS_EX_RP2040.zip](https://github.com/goshante/ats20_ats_ex/files/15205843/ATS_EX_RP2040.zip)

![GMkh7jjaAAAXMXa](https://github.com/goshante/ats20_ats_ex/assets/3067670/a74d6c9e-2da4-406e-a56d-ea1c87372498)

**Comment by goshante** [comment]
Looks interesting, but I am working on other projects now and have no future plans for working on receiver's firmware
